# tasks/main.yml
# Configure Zabbix server
---
- name: Ensure that extra packages are installed
  yum:
    name: ['policycoreutils-python', 'firewalld', 'python-firewall']
    state: installed

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes  

- name: Change the zabbix_t SELinux domain to permissive
  selinux_permissive:
    name: zabbix_t
    permissive: true
  register: selinux_permissive_zabbix_t

- name: Restart zabbix-server service after SELinux changes
  service:
    name: zabbix-server
    state: restarted
  when: selinux_permissive_zabbix_t is changed

- name: Open Zabbix server port in firewall
  firewalld:
    port: 10051/tcp
    permanent: yes
    state: enabled
  register: firewall10051

- name: Reload firewall
  command: firewall-cmd --reload
  when: firewall10051 is changed
  register: firewallcmdout

- debug: 
    var: firewallcmdout

- name: Zabbix OpsGenie configuration
  block: 
    name: Install Zabbix OpsGenie plugin
    yum:
      name: https://s3-us-west-2.amazonaws.com/opsgeniedownloads/repo/opsgenie-zabbix-2.22.0-1.all.noarch.rpm
      state: present
  when: zabbix_server_opsgenie_integration